# Generated by Django 4.0.3 on 2022-03-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('audio_path', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='post_pics')),
            ],
        ),
    ]
